### ISSUE TITLE
Add more than one account to the .env

### ISSUE THREAD

**Issue by AritzUMA** [sekai-soft/nitter#4]
Hi everybody,

first of all thanks to @sekai-soft for this work. I wanted to know if is possible add more than one account to the .env to avoid the rate limited error.

Thanks

**Comment by Danijel-Enoch** [comment]
Hello, i am having issues with nginx locally,
![Screenshot 2024-10-04 at 04 38 51](https://github.com/user-attachments/assets/4a5ca3eb-58a8-4d05-a94e-860ccf6ff0fd)

**Comment by yacxnn** [comment]
same problem. Any solution ?

**Comment by KTachibanaM** [comment]
It's now supported. Check https://github.com/sekai-soft/guide-nitter-self-hosting/blob/master/docs/server.md#multiple-twitter-accounts
